#!/bin/sh

# Strip down the packages the I don't need on a gnome debian 12 setup.

sudo apt purge -y libreoffice-common \
gnome-contacts gnome-weather gnome-clocks gnome-maps totem \
gnome-calendar simple-scan gnome-snapshot gnome-logs \
firefox-esr evolution yelp gnome-font-viewer gnome-characters \
shotwell evince loupe gnome-sound-recorder gnome-disk-utility \
gnome-music seahorse im-config malcontent gnome-calculator \
gnome-tour gnome-connections nm-connection-editor

sudo rm -r /etc/libreoffice/registry

# Manually install as to not be deleted later by autoremove.
sudo apt install -y network-manager

# Delete unnecessary dependencies
sudo apt autoremove -y --purge
